INSERT INTO distritos (id,nombre) VALUES(1,'Lince');
INSERT INTO distritos (id,nombre) VALUES(2,'Los olivos');
INSERT INTO distritos (id,nombre) VALUES(3,'Lurigancho');
INSERT INTO distritos (id,nombre) VALUES(4,'Lurín');
INSERT INTO distritos (id,nombre) VALUES(5,'Miraflores');
INSERT INTO distritos (id,nombre) VALUES(6,'Chorrillos');
INSERT INTO distritos (id,nombre) VALUES(7,'Cieneguilla');
INSERT INTO distritos (id,nombre) VALUES(8,'Cercado de Lima');
INSERT INTO distritos (id,nombre) VALUES(9,'Carabayllo');
INSERT INTO distritos (id,nombre) VALUES(10,'Breña');
INSERT INTO distritos (id,nombre) VALUES(11,'Barranco');
INSERT INTO distritos (id,nombre) VALUES(12,'Ate');

INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(1,'walter','matos','walter@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(2,'marco','matos','marco@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(3,'kevin','matos','kevin@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(4,'Raul','matos','raul@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(5,'Akemi','Higa','Akemi@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(6,'Brandon','Villegas','Brandon@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(7,'Milagros','Granda','milagros@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(8,'Diana','Clemente','DianaClemente@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(9,'Romina','Matos','Romina@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(10'Chino','Risas','chino@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(11,'Mario','vargas','mario@gmail.com','2023-01-03');
INSERT into clientes (idDistrito,nombre,apellido,email,createat) VALUES(12,'Carlos','vera','carlos_vera@gmail.com','2023-01-03');
